# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Build Pipeline

on:          
  push:
    branches: [ master ]
    paths-ignore:
      - '.github/**'
      - 'version.txt'  
  workflow_dispatch: 

jobs:
  unit-test:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        catch: maven
        
    - name: Unit Testing
      run: | 
          mvn test
          ls -l
          
  build:
    #runs-on: ubuntu-latest
    needs: [unit-test]

    steps:
    #- uses: actions/checkout@v2
    
    uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        catch: maven    
    
    - name: Build Package
      run: | 
          mvn install -DskipTests
          ls -l


        
    
